import type { UniversalEvidenceNode } from '../../types/universalEvidence.js';
import type { FusionTier } from '../../agents/fusionAgent/types.js';

export interface FusionTestCase {
  id: string;
  category: 'D' | 'E' | 'F' | 'G' | 'H';
  description: string;
  input: UniversalEvidenceNode[];
  expected: {
    canonicalFormula?: string;
    formulaTier?: FusionTier;
    polymorphTier?: FusionTier;
    isSurfaceBulkDiscrepancy?: boolean;
    hasContradiction?: boolean;
    hasSameOriginCaveat?: boolean;
    polymorphNotCorroborated?: boolean;
  };
}

const now = new Date().toISOString();

export const FUSION_GROUND_TRUTH_CASES: FusionTestCase[] = [
  // Category D: Agreement (~4 cases)
  {
    id: 'fus-d1-tio2',
    category: 'D',
    description: 'Independent XRD and Raman evidence agreeing on TiO2 Anatase.',
    input: [
      {
        id: 'd1-xrd',
        technique: 'XRD',
        primaryAxis: 25.3,
        primaryAxisUnit: '°2θ',
        value: 0.95,
        valueUnit: 'score',
        label: 'Anatase',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-tio2',
          processingHash: 'hash-xrd-tio2',
          formula: 'TiO2',
        },
      },
      {
        id: 'd1-raman',
        technique: 'Raman',
        primaryAxis: 144,
        primaryAxisUnit: 'cm⁻¹',
        value: 0.90,
        valueUnit: 'score',
        label: 'Anatase Eg mode',
        concept: 'vibrational',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-raman-tio2',
          processingHash: 'hash-raman-tio2',
          formula: 'TiO2',
        },
      },
    ],
    expected: {
      canonicalFormula: 'TiO2',
      formulaTier: 'CORROBORATED',
    },
  },
  {
    id: 'fus-d2-fe3o4',
    category: 'D',
    description: 'Independent XRD and FTIR evidence agreeing on Fe3O4 Magnetite.',
    input: [
      {
        id: 'd2-xrd',
        technique: 'XRD',
        primaryAxis: 35.8,
        primaryAxisUnit: '°2θ',
        value: 0.92,
        valueUnit: 'score',
        label: 'Magnetite',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-fe3o4',
          processingHash: 'hash-xrd-fe3o4',
          formula: 'Fe3O4',
        },
      },
      {
        id: 'd2-ftir',
        technique: 'FTIR',
        primaryAxis: 570,
        primaryAxisUnit: 'cm⁻¹',
        value: 0.88,
        valueUnit: 'score',
        label: 'Fe-O band',
        concept: 'vibrational',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-ftir-fe3o4',
          processingHash: 'hash-ftir-fe3o4',
          formula: 'Fe3O4',
        },
      },
    ],
    expected: {
      canonicalFormula: 'Fe3O4',
      formulaTier: 'CORROBORATED',
    },
  },
  {
    id: 'fus-d3-zno',
    category: 'D',
    description: 'Independent XRD and XPS evidence agreeing on ZnO Zincite.',
    input: [
      {
        id: 'd3-xrd',
        technique: 'XRD',
        primaryAxis: 36.2,
        primaryAxisUnit: '°2θ',
        value: 0.94,
        valueUnit: 'score',
        label: 'Zincite',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-zno',
          processingHash: 'hash-xrd-zno',
          formula: 'ZnO',
        },
      },
      {
        id: 'd3-xps',
        technique: 'XPS',
        primaryAxis: 1021.7,
        primaryAxisUnit: 'eV',
        value: 0.91,
        valueUnit: 'score',
        label: 'Zn2+',
        concept: 'oxidation_state',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xps-zno',
          processingHash: 'hash-xps-zno',
          summary: 'Zn2+ 2p3/2 peak at 1021.7 eV',
        },
      },
    ],
    expected: {
      canonicalFormula: 'ZnO',
      formulaTier: 'CORROBORATED',
    },
  },
  {
    id: 'fus-d4-fe2o3',
    category: 'D',
    description: 'Independent XRD and Raman evidence agreeing on Fe2O3 Hematite.',
    input: [
      {
        id: 'd4-xrd',
        technique: 'XRD',
        primaryAxis: 33.1,
        primaryAxisUnit: '°2θ',
        value: 0.93,
        valueUnit: 'score',
        label: 'Hematite',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-fe2o3',
          processingHash: 'hash-xrd-fe2o3',
          formula: 'Fe2O3',
        },
      },
      {
        id: 'd4-raman',
        technique: 'Raman',
        primaryAxis: 226,
        primaryAxisUnit: 'cm⁻¹',
        value: 0.89,
        valueUnit: 'score',
        label: 'Hematite A1g mode',
        concept: 'vibrational',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-raman-fe2o3',
          processingHash: 'hash-raman-fe2o3',
          formula: 'Fe2O3',
        },
      },
    ],
    expected: {
      canonicalFormula: 'Fe2O3',
      formulaTier: 'CORROBORATED',
    },
  },
  {
    id: 'fus-d5-cuo-recovery',
    category: 'D',
    description: 'Multi-technique recovery combining low-confidence XRD (CuO), Raman (Tenorite), and XPS (Cu²⁺).',
    input: [
      {
        id: 'd5-xrd',
        technique: 'XRD',
        primaryAxis: 35.5,
        primaryAxisUnit: '°2θ',
        value: 0.45,
        valueUnit: 'score',
        label: 'Tenorite CuO',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'low',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-cuo-rec',
          processingHash: 'hash-xrd-cuo-rec',
          formula: 'CuO',
        },
      },
      {
        id: 'd5-raman',
        technique: 'Raman',
        primaryAxis: 298,
        primaryAxisUnit: 'cm⁻¹',
        value: 0.50,
        valueUnit: 'score',
        label: 'Tenorite Ag mode',
        concept: 'vibrational',
        role: 'primary',
        confidence: 'low',
        provenance: {
          createdAt: now,
          datasetId: 'ds-raman-cuo-rec',
          processingHash: 'hash-raman-cuo-rec',
          formula: 'CuO',
        },
      },
      {
        id: 'd5-xps',
        technique: 'XPS',
        primaryAxis: 933.6,
        primaryAxisUnit: 'eV',
        value: 0.60,
        valueUnit: 'score',
        label: 'Cu²⁺',
        concept: 'chemical_state',
        role: 'supporting',
        confidence: 'medium',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xps-cuo-rec',
          processingHash: 'hash-xps-cuo-rec',
          formula: 'CuO',
        },
      },
    ],
    expected: {
      canonicalFormula: 'CuO',
      formulaTier: 'CORROBORATED',
    },
  },

  // Category E: Contradiction (~3 cases)
  {
    id: 'fus-e1-tio2-ti0',
    category: 'E',
    description: 'Contradiction between XRD indicating TiO2 oxide and XPS indicating metallic Ti0.',
    input: [
      {
        id: 'e1-xrd',
        technique: 'XRD',
        primaryAxis: 25.3,
        primaryAxisUnit: '°2θ',
        value: 0.90,
        valueUnit: 'score',
        label: 'Anatase',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-e1',
          processingHash: 'hash-xrd-e1',
          formula: 'TiO2',
        },
      },
      {
        id: 'e1-xps',
        technique: 'XPS',
        primaryAxis: 454.0,
        primaryAxisUnit: 'eV',
        value: 0.85,
        valueUnit: 'score',
        label: 'Ti0',
        concept: 'oxidation_state',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xps-e1',
          processingHash: 'hash-xps-e1',
          summary: 'Ti0 metallic peak at 454.0 eV',
        },
      },
    ],
    expected: {
      formulaTier: 'CONTESTED',
      hasContradiction: true,
    },
  },
  {
    id: 'fus-e2-fe2o3-fe0',
    category: 'E',
    description: 'Contradiction between XRD indicating Fe2O3 oxide and XPS indicating metallic Fe0.',
    input: [
      {
        id: 'e2-xrd',
        technique: 'XRD',
        primaryAxis: 33.1,
        primaryAxisUnit: '°2θ',
        value: 0.92,
        valueUnit: 'score',
        label: 'Hematite',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-e2',
          processingHash: 'hash-xrd-e2',
          formula: 'Fe2O3',
        },
      },
      {
        id: 'e2-xps',
        technique: 'XPS',
        primaryAxis: 706.8,
        primaryAxisUnit: 'eV',
        value: 0.87,
        valueUnit: 'score',
        label: 'Fe0',
        concept: 'oxidation_state',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xps-e2',
          processingHash: 'hash-xps-e2',
          summary: 'Fe0 metallic peak at 706.8 eV',
        },
      },
    ],
    expected: {
      formulaTier: 'CONTESTED',
      hasContradiction: true,
    },
  },
  {
    id: 'fus-e3-zno-zn0',
    category: 'E',
    description: 'Contradiction between XRD indicating ZnO oxide and XPS indicating metallic Zn0.',
    input: [
      {
        id: 'e3-xrd',
        technique: 'XRD',
        primaryAxis: 36.2,
        primaryAxisUnit: '°2θ',
        value: 0.91,
        valueUnit: 'score',
        label: 'Zincite',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-e3',
          processingHash: 'hash-xrd-e3',
          formula: 'ZnO',
        },
      },
      {
        id: 'e3-xps',
        technique: 'XPS',
        primaryAxis: 1021.0,
        primaryAxisUnit: 'eV',
        value: 0.88,
        valueUnit: 'score',
        label: 'Zn0',
        concept: 'oxidation_state',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xps-e3',
          processingHash: 'hash-xps-e3',
          summary: 'Zn0 metallic peak at 1021.0 eV',
        },
      },
    ],
    expected: {
      formulaTier: 'CONTESTED',
      hasContradiction: true,
    },
  },

  // Category F: Surface/bulk discrepancy (~2 cases)
  {
    id: 'fus-f1-cu2o-cu2',
    category: 'F',
    description: 'Surface stratification: XRD shows bulk Cu2O cuprite while XPS detects Cu2+ oxide surface layer.',
    input: [
      {
        id: 'f1-xrd',
        technique: 'XRD',
        primaryAxis: 36.4,
        primaryAxisUnit: '°2θ',
        value: 0.92,
        valueUnit: 'score',
        label: 'Cuprite',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-f1',
          processingHash: 'hash-xrd-f1',
          formula: 'Cu2O',
        },
      },
      {
        id: 'f1-xps',
        technique: 'XPS',
        primaryAxis: 933.6,
        primaryAxisUnit: 'eV',
        value: 0.88,
        valueUnit: 'score',
        label: 'Cu2+',
        concept: 'oxidation_state',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xps-f1',
          processingHash: 'hash-xps-f1',
          summary: 'Cu2+ oxide surface layer at 933.6 eV',
        },
      },
    ],
    expected: {
      isSurfaceBulkDiscrepancy: true,
      hasContradiction: false,
    },
  },
  {
    id: 'fus-f2-fe3o4-fe3',
    category: 'F',
    description: 'Intrinsic mixed-valence: XRD shows bulk Fe3O4 magnetite and XPS detects Fe3+ (intrinsic to bulk Fe3O4). Should NOT flag surface stratification.',
    input: [
      {
        id: 'f2-xrd',
        technique: 'XRD',
        primaryAxis: 35.8,
        primaryAxisUnit: '°2θ',
        value: 0.93,
        valueUnit: 'score',
        label: 'Magnetite',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-f2',
          processingHash: 'hash-xrd-f2',
          formula: 'Fe3O4',
        },
      },
      {
        id: 'f2-xps',
        technique: 'XPS',
        primaryAxis: 711.0,
        primaryAxisUnit: 'eV',
        value: 0.89,
        valueUnit: 'score',
        label: 'Fe3+',
        concept: 'oxidation_state',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xps-f2',
          processingHash: 'hash-xps-f2',
          summary: 'Fe3+ oxidized surface layer at 711.0 eV',
        },
      },
    ],
    expected: {
      isSurfaceBulkDiscrepancy: false,
      hasContradiction: false,
    },
  },

  // Category G: Independence guard (~2 cases)
  {
    id: 'fus-g1-same-origin-tio2',
    category: 'G',
    description: 'Independence guard: XRD and Raman sharing the exact same processingHash cannot reach CORROBORATED tier.',
    input: [
      {
        id: 'g1-xrd',
        technique: 'XRD',
        primaryAxis: 25.3,
        primaryAxisUnit: '°2θ',
        value: 0.90,
        valueUnit: 'score',
        label: 'Anatase',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-shared-g1',
          processingHash: 'shared-hash-g1',
          formula: 'TiO2',
        },
      },
      {
        id: 'g1-raman',
        technique: 'Raman',
        primaryAxis: 144,
        primaryAxisUnit: 'cm⁻¹',
        value: 0.88,
        valueUnit: 'score',
        label: 'Anatase',
        concept: 'vibrational',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-shared-g1',
          processingHash: 'shared-hash-g1',
          formula: 'TiO2',
        },
      },
    ],
    expected: {
      hasSameOriginCaveat: true,
    },
  },
  {
    id: 'fus-g2-same-origin-zno',
    category: 'G',
    description: 'Independence guard: XRD and XPS sharing the exact same processingHash cannot reach CORROBORATED tier.',
    input: [
      {
        id: 'g2-xrd',
        technique: 'XRD',
        primaryAxis: 36.2,
        primaryAxisUnit: '°2θ',
        value: 0.92,
        valueUnit: 'score',
        label: 'Zincite',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-shared-g2',
          processingHash: 'shared-hash-g2',
          formula: 'ZnO',
        },
      },
      {
        id: 'g2-xps',
        technique: 'XPS',
        primaryAxis: 1021.7,
        primaryAxisUnit: 'eV',
        value: 0.89,
        valueUnit: 'score',
        label: 'Zn2+',
        concept: 'oxidation_state',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-shared-g2',
          processingHash: 'shared-hash-g2',
          summary: 'Zn2+ peak at 1021.7 eV',
        },
      },
    ],
    expected: {
      hasSameOriginCaveat: true,
    },
  },

  // Category H: Polymorph cap (~2 cases)
  {
    id: 'fus-h1-polymorph-tio2',
    category: 'H',
    description: 'Polymorph cap: XPS formula-level confirmation cannot raise polymorph tier above SINGLE-SOURCE cap.',
    input: [
      {
        id: 'h1-xrd',
        technique: 'XRD',
        primaryAxis: 25.3,
        primaryAxisUnit: '°2θ',
        value: 0.95,
        valueUnit: 'score',
        label: 'Anatase',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-h1',
          processingHash: 'hash-xrd-h1',
          formula: 'TiO2',
        },
      },
      {
        id: 'h1-xps',
        technique: 'XPS',
        primaryAxis: 458.6,
        primaryAxisUnit: 'eV',
        value: 0.92,
        valueUnit: 'score',
        label: 'Ti4+',
        concept: 'oxidation_state',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xps-h1',
          processingHash: 'hash-xps-h1',
          summary: 'Ti4+ 2p3/2 peak at 458.6 eV',
        },
      },
    ],
    expected: {
      canonicalFormula: 'TiO2',
      formulaTier: 'CORROBORATED',
      polymorphTier: 'SINGLE-SOURCE',
      polymorphNotCorroborated: true,
    },
  },
  {
    id: 'fus-h2-polymorph-fe2o3',
    category: 'H',
    description: 'Polymorph cap: XPS formula-level confirmation cannot raise Fe2O3 polymorph tier above SINGLE-SOURCE cap.',
    input: [
      {
        id: 'h2-xrd',
        technique: 'XRD',
        primaryAxis: 33.1,
        primaryAxisUnit: '°2θ',
        value: 0.93,
        valueUnit: 'score',
        label: 'Hematite',
        concept: 'crystalline',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xrd-h2',
          processingHash: 'hash-xrd-h2',
          formula: 'Fe2O3',
        },
      },
      {
        id: 'h2-xps',
        technique: 'XPS',
        primaryAxis: 711.0,
        primaryAxisUnit: 'eV',
        value: 0.90,
        valueUnit: 'score',
        label: 'Fe3+',
        concept: 'oxidation_state',
        role: 'primary',
        confidence: 'high',
        provenance: {
          createdAt: now,
          datasetId: 'ds-xps-h2',
          processingHash: 'hash-xps-h2',
          summary: 'Fe3+ 2p3/2 peak at 711.0 eV',
        },
      },
    ],
    expected: {
      canonicalFormula: 'Fe2O3',
      formulaTier: 'CORROBORATED',
      polymorphTier: 'SINGLE-SOURCE',
      polymorphNotCorroborated: true,
    },
  },
];
